[2024-08-07T15:40:40.617+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-07T15:40:40.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_prueba_tecnica.ingesta scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-08-07T15:40:40.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_prueba_tecnica.ingesta scheduled__2024-08-06T00:00:00+00:00 [queued]>
[2024-08-07T15:40:40.640+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-08-07T15:40:40.652+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingesta> on 2024-08-06 00:00:00+00:00
[2024-08-07T15:40:40.658+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=62) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-07T15:40:40.659+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_prueba_tecnica', 'ingesta', 'scheduled__2024-08-06T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/dag_prueba_tecnica.py', '--cfg-path', '/tmp/tmpopbr6exp']
[2024-08-07T15:40:40.660+0000] {standard_task_runner.py:64} INFO - Started process 100 to run task
[2024-08-07T15:40:40.660+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask ingesta
[2024-08-07T15:40:40.697+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_prueba_tecnica.ingesta scheduled__2024-08-06T00:00:00+00:00 [running]> on host 278ba5711b2c
[2024-08-07T15:40:40.759+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='miguel_guimarey' AIRFLOW_CTX_DAG_ID='dag_prueba_tecnica' AIRFLOW_CTX_TASK_ID='ingesta' AIRFLOW_CTX_EXECUTION_DATE='2024-08-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-06T00:00:00+00:00'
[2024-08-07T15:40:40.760+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-07T15:40:41.931+0000] {warnings.py:112} WARNING - /opt/***/dags/dag_prueba_tecnica.py:29: DtypeWarning: Columns (46,56,59) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/opt/***/dags/dataset.csv', delimiter=';').to_json(orient='records')

[2024-08-07T15:40:44.100+0000] {logging_mixin.py:188} INFO - Se lee el dataset de datos
[2024-08-07T15:40:44.100+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-07T15:40:44.101+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_prueba_tecnica.py", line 36, in ingestaDatos
    df.to_sql('customers', pg_hook.get_sqlalchemy_engine(), if_exists='replace')
    ^^^^^^^^^
AttributeError: 'str' object has no attribute 'to_sql'
[2024-08-07T15:40:44.111+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_prueba_tecnica, task_id=ingesta, run_id=scheduled__2024-08-06T00:00:00+00:00, execution_date=20240806T000000, start_date=20240807T154040, end_date=20240807T154044
[2024-08-07T15:40:44.125+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 114 for task ingesta ('str' object has no attribute 'to_sql'; 100)
[2024-08-07T15:40:44.164+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-07T15:40:44.187+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-07T15:40:44.199+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
